# Generated by Django 5.2.12 on 2026-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='threat_type',
        ),
        migrations.AddField(
            model_name='threat',
            name='indicators',
            field=models.TextField(default=''),
        ),
    ]
