# Generated by Django 5.2.12 on 2026-03-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_remove_threat_threat_type_threat_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(default='Suspicious', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threat',
            name='indicators',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='threat',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='threat',
            name='severity',
            field=models.CharField(max_length=10),
        ),
    ]
