# Generated by Django 5.2.12 on 2026-03-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('threats', '0003_threat_threat_type_alter_threat_indicators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(default='Suspicious', max_length=50),
        ),
    ]
