# Generated by Django 5.2.12 on 2026-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_threat_post_alter_threat_threat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='vt_detections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(max_length=100),
        ),
    ]
