# Generated by Django 5.2.12 on 2026-03-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0005_threat_vt_detections_alter_threat_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='abuseipdb_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
